### ISSUE TITLE
Disable gracefully on Windows

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#311]
AppSignal should install and be able to run the `appsignal` tasks. The integration itself should always be disabled.

**Comment by tombruijn** [comment]
I've been testing the gem on Windows. This is what I have so far.

## Gem installation

The gem installation itself works as long as the DevKit is installed on Windows. I'll update the docs to mention this.

## AppSignal install

Result of `appsignal install PUSH_API_KEY`:

```
PS C:\Users\User\Desktop\test_app> bundle exec appsignal install PUSH_API_KEY
C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal/config.rb:8:in `realpath': No such file or directory @ realpath_rec - /tmp (Errno::ENOENT)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal/config.rb:8:in `<class:Config>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal/config.rb:7:in `<module:Appsignal>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal/config.rb:6:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal.rb:694:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal.rb:694:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal/cli.rb:4:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/lib/appsignal/cli.rb:4:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/bin/appsignal:4:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/appsignal-2.2.1/bin/appsignal:4:in `<top (required)>'
        from C:/Ruby23/bin/appsignal:22:in `load'
        from C:/Ruby23/bin/appsignal:22:in `<main>'
```

Looks like the `appsignal install` command line tool broken in #219/#158 and potentially a change before that where we fall back on `/tmp` as a log path.

We need to fix the error and output a message that we can't automatically send demo samples on windows and users should test AppSignal on another OS to send data to the AppSignal servers.

---

## AppSignal diagnose

AppSignal diagnose after #267. Currently breaks on parsing JSON from a stubbed extension method that returns nil.

```
PS C:\Users\User\Desktop\test_app> bundle exec appsignal diagnose
AppSignal diagnose
================================================================================
Use this information to debug your configuration.
More information is available on the documentation site.
http://docs.appsignal.com/
Send this output to support@appsignal.com if you need help.
================================================================================

AppSignal library
  Gem version: 2.2.1
  Agent version: da45785
  Gem install path: C:/Users/User/Desktop/appsignal-ruby
  Extension loaded: false

Host information
  Architecture: i686
  Operating System: mingw32
  Ruby version: 2.3.0-p222
  root user: true (not recommended)
  Running in container:

appsignal: Unable to log to 'C:/Users/User/Desktop/test_app/log'. Logging to 'C:/Users/User/AppData/Local/Temp' instead. Please check the permissions for the application's (log) directory.
appsignal: Unable to log to 'C:/Users/User/Desktop/test_app/log'. Logging to 'C:/Users/User/AppData/Local/Temp' instead. Please check the permissions for the application's (log) directory.
Agent diagnostics
no implicit conversion of nil into String
C:/Ruby23/lib/ruby/2.3.0/json/common.rb:156:in `initialize'
C:/Ruby23/lib/ruby/2.3.0/json/common.rb:156:in `new'
C:/Ruby23/lib/ruby/2.3.0/json/common.rb:156:in `parse'
C:/Users/User/Desktop/appsignal-ruby/lib/appsignal/cli/diagnose.rb:179:in `run_agent_diagnose_mode'
C:/Users/User/Desktop/appsignal-ruby/lib/appsignal/cli/diagnose.rb:82:in `run'
C:/Users/User/Desktop/appsignal-ruby/lib/appsignal/cli.rb:32:in `run'
C:/Users/User/Desktop/appsignal-ruby/bin/appsignal:7:in `<top (required)>'
C:/Ruby23/lib/ruby/gems/2.3.0/bin/appsignal:22:in `load'
C:/Ruby23/lib/ruby/gems/2.3.0/bin/appsignal:22:in `<main>'
```

Should rescue that exception and print a message that we can't parse the extension's report.
Perhaps mention with the OS that windows is not supported.

## AppSignal demo

The demo command doesn't work, but since it's a tool mostly relying on the extension and agent it would be weird if it did work. Since it doesn't really crash no change is needed here.

```
PS C:\Users\User\Desktop\test_app> bundle exec appsignal demo
Sending demonstration sample data...
[2017-06-14T02:19:36 (process) #6024][ERROR] appsignal: Failed to load extension (cannot load such file -- appsignal_extension), please check the install.log file in the ext directory of the gem and e-mail us at support@ap
psignal.com
[2017-06-14T02:19:36 (process) #6024][INFO] appsignal: Not starting appsignal, extension is not loaded
Error: Unable to start the AppSignal agent and send data to AppSignal.com
Please use `appsignal diagnose` to debug your configuration.
```
