### ISSUE TITLE
Ruby 2.6.4  Failed to load extension 

### ISSUE THREAD

**Issue by ifsc01** [appsignal/appsignal-ruby#560]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

```
 [INFO] appsignal: Loading Rails (6.0.0) integration
[2019-09-21T14:35:46 (process) #16][ERROR] appsignal: Failed to load extension (cannot load such file -- appsignal_extension), please run `appsignal diagnose` and email us at support@appsignal.com
[2019-09-21T14:35:46 (process) #16][INFO] appsignal: Loading Rails (6.0.0) integration
[2019-09-21T14:35:46 (process) #16][INFO] Not starting appsignal, extension is not loaded
[2019-09-21T14:35:46 (process) #15][INFO] Not starting appsignal, extension is not loaded

```
## To Reproduce

- Using AppSignal for Ruby gem version 2.9.13
- ruby:2.6.4-alpine3.10
- Rails 6

**Comment by tombruijn** [comment]
Hi @ifsc01,

Have you installed the necessary packages for Alpine Linux on your machine? See the list in our docs: https://docs.appsignal.com/support/operating-systems.html#alpine-linux

If so, can you send us a diagnose report? Run this command on your Alpine Linux machine:

```
appsignal diagnose --send-report
```

**Comment by ifsc01** [comment]
@tombruijn https://appsignal.com/diagnose_reports/diagc237d1cab3fbcd86b077?linked=true

**Comment by tombruijn** [comment]
Hi @ifsc01,

Looks like our CDN from which the AppSignal agent & extension are downloaded can't be reached from your end.

Can you update to version 2.9.14 of our Ruby gem (just released) and see if that does work?
We've added a mirror from which our agent & extension package will be downloaded in that version.

**Comment by ifsc01** [comment]
@tombruijn may be blocked by china GFW

**Comment by tombruijn** [comment]
@ifsc01 yes, that's what we're thinking. Another user managed to install it when using the mirror that we added in the latest release. Did that work for you?

**Comment by ifsc01** [comment]
install report 

```
bash-5.0# cat install.report
---
result:
  status: error
  error: 'Net::OpenTimeout: execution expired'
  backtrace:
  - "/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize'"
  - "/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `open'"
  - "/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'"
  - "/usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'"
  - "/usr/local/lib/ruby/2.6.0/net/http.rb:945:in `connect'"
  - "/usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'"
  - "/usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:224:in `catch'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:736:in `open'"
  - "/usr/local/lib/ruby/2.6.0/open-uri.rb:35:in `open'"
  - "/usr/local/bundle/gems/appsignal-2.9.13/ext/base.rb:110:in `download_archive'"
  - extconf.rb:19:in `install'
  - extconf.rb:89:in `<main>'
language:
  name: ruby
  version: 2.6.0-p104
  implementation: ruby
download:
  checksum: unverified
  download_url: https://appsignal-agent-releases.global.ssl.fastly.net/e1c9363/appsignal-x86_64-linux-musl-all-static.tar.gz
build:
  time: 2019-09-24 17:50:28.559909041 Z
  package_path: "/usr/local/bundle/gems/appsignal-2.9.13"
  architecture: x86_64
  target: linux-musl
  musl_override: false
  dependencies: {}
  flags: {}
  library_type: static
  source: remote
host:
  root_user: true
  dependencies: {}
bash-5.0#
```
NO request to `https://d135dj0rjqvssy.cloudfront.net`

**Comment by ifsc01** [comment]
```
[root@cmcm-devel-c ~]# curl https://d135dj0rjqvssy.cloudfront.net
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>1F8C50DE92C24AB6</RequestId><HostId>Xvrnv0wdpeeYJynF5PDmSz/G6y0Fz9U9e5ndRzrsbOtEATK4mYvHLAV1IOaN27vlT/f4FF/LzW0=</HostId></Error>[root@cmcm-devel-c ~]#
[root@cmcm-devel-c ~]#
[root@cmcm-devel-c ~]#
[root@cmcm-devel-c ~]# curl https://appsignal-agent-releases.global.ssl.fastly.net


^C
```

**Comment by ifsc01** [comment]
diagnose_reports  https://appsignal.com/diagnose_reports/diaga7e0c959dab57ee2e4a3?linked=true

**Comment by tombruijn** [comment]
Hi @ifsc01 , I see you're using the 2.9.13 release. The installation mirror was added in 2.9.14. Can you upgrade to that and let me know if that worked?

You can also test manually if the other mirror worked from your host with this command:

```
curl -O https://d135dj0rjqvssy.cloudfront.net/e1c9363/appsignal-x86_64-linux-musl-all-static.tar.gz
```

The root path always return a HTTP 403 error.

**Comment by ifsc01** [comment]
It works



[2019-09-24T18:34:38 (process) #8][INFO] appsignal: Loading Rails (6.0.0) integration
[2019-09-24T18:34:39 (process) #8][INFO] Starting AppSignal 2.9.15 (bin/rails, Ruby 2.6.4, x86_64-linux-musl)
[2019-09-24T18:34:39 (process) #8][INFO] Installing action_cable hook
[2019-09-24T18:34:39 (process) #8][INFO] Installing active_support_notifications hook
[2019-09-24T18:34:39 (process) #8][INFO] Installing net_http hook
[2019-09-24T18:34:39 (process) #8][INFO] Installing puma hook
[2019-09-24T18:34:39 (process) #8][INFO] Installing rake hook
[2019-09-24T18:34:39 (process) #8][INFO] Installing redis hook
[2019-09-24T18:34:39 (process) #8][INFO] Installing sidekiq hook
[2019-09-24T18:34:38 (process) #6][INFO] appsignal: Loading Rails (6.0.0) integration
[2019-09-24T18:34:39 (process) #6][INFO] Starting AppSignal 2.9.15 (/usr/local/bundle/bin/sidekiq, Ruby 2.6.4, x86_64-linux-musl)
[2019-09-24T18:34:39 (process) #6][INFO] Installing action_cable hook
[2019-09-24T18:34:39 (process) #6][INFO] Installing active_support_notifications hook
[2019-09-24T18:34:39 (process) #6][INFO] Installing net_http hook
[2019-09-24T18:34:39 (process) #6][INFO] Installing puma hook
[2019-09-24T18:34:39 (process) #6][INFO] Installing rake hook
[2019-09-24T18:34:39 (process) #6][INFO] Installing redis hook
[2019-09-24T18:34:39 (process) #6][INFO] Installing sidekiq hook

**Comment by tombruijn** [comment]
Great to hear!!

**Comment by ifsc01** [comment]
@tombruijn How about adding one aliyun oss (china area) mirror? I can do this

for example 

https://appsignal.oss-cn-beijing.aliyuncs.com/ 

https://appsignal.oss-cn-beijing.aliyuncs.com/e1c9363/appsignal-x86_64-linux-musl-all-static.tar.gz

**Comment by tombruijn** [comment]
Hi @ifsc01,

We discussed it with the team and decided not to add a China area based mirror at this moment. The backup cloudfront mirror we added should not be blocked in your area. We're talking to our provider for the main download location about fixing access in the China area.

If you are having trouble downloading our agent & extension in the future, please let us know at support@appsignal.com so we can contact our providers about the issue and add additional mirrors then.
