### ISSUE TITLE
Missing extension methods raise error on extension installation failure

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#719]
When the AppSignal extension fails to install, it should disable itself without raising any errors. Unfortunately it does when you create a transaction directly (not using the `monitor_transaction` helper) or send a metric.

I tested this in the [ruby/single-task](https://github.com/appsignal/test-setups/tree/28c6c8627d73e6a534af684b1d1b2bd9d6e9d738/ruby/single-task) and [ruby/jruby-single-task](https://github.com/appsignal/test-setups/tree/28c6c8627d73e6a534af684b1d1b2bd9d6e9d738/ruby/jruby-single-task) apps.

The changes for the ruby/single-task app (the same set of changes should be made to the ruby/jruby-single-task app directory) are listed below.

## Transaction

Creating a transaction without any helpers, like we do in most integrations nowadays.
Same changes can be made in the ruby/jruby-single-task app.

```diff
diff --git ruby/single-task/app/app.rb ruby/single-task/app/app.rb
index adb3ead..d643115 100644
--- ruby/single-task/app/app.rb
+++ ruby/single-task/app/app.rb
@@ -26,13 +26,25 @@ class Monitor
+require "securerandom"
 20.times do |i|
-  Appsignal.monitor_transaction("perform_job.monitor", :class => "Monitor", :method => "loop") do
-    Monitor.new.perform("foo", { :foo => i }, foo: i, bar: i.even?)
-  end
+  transaction = Appsignal::Transaction.create(
+    SecureRandom.uuid,
+    Appsignal::Transaction::HTTP_REQUEST,
+    Appsignal::Transaction::GenericRequest.new({})
+  )
+  Monitor.new.perform("foo", { :foo => i }, foo: i, bar: i.even?)
+  transaction.set_action_if_nil("Test#test")
+  Appsignal::Transaction.complete_current!
+
   sleep 1
 end

diff --git ruby/single-task/docker-compose.yml ruby/single-task/docker-compose.yml
index 24f8baf..fdad427 100644
--- ruby/single-task/docker-compose.yml
+++ ruby/single-task/docker-compose.yml
@@ -6,6 +6,7 @@ services:
     image: ruby/single-task
     environment:
       - APPSIGNAL_APP_NAME=ruby-single-task
+      - _TEST_APPSIGNAL_EXTENSION_FAILURE=true
     env_file:
       - ../../appsignal.env
       - ../../appsignal_key.env
````

## Metrics

```ruby
# In Ruby it trips on adding tags to a data object
Appsignal.increment_counter "foo", 1, { "foo" => "bar" }
# In JRuby this is enough, just creating the data object for an empty hash
Appsignal.increment_counter "foo", 1
```

Same changes can be made in the ruby/jruby-single-task app.

```diff
diff --git ruby/single-task/app/app.rb ruby/single-task/app/app.rb
index adb3ead..2422743 100644
--- ruby/single-task/app/app.rb
+++ ruby/single-task/app/app.rb
@@ -26,6 +26,7 @@ class Monitor
       puts "Monitor is doing stuff. Params: #{param1}, #{options}, #{foo}, #{bar}"
       sleep 1
     end
+    Appsignal.increment_counter "foo", 1, { "foo" => "bar" }
   end
   appsignal_instrument_method :perform
 end

diff --git ruby/single-task/docker-compose.yml ruby/single-task/docker-compose.yml
index 24f8baf..fdad427 100644
--- ruby/single-task/docker-compose.yml
+++ ruby/single-task/docker-compose.yml
@@ -6,6 +6,7 @@ services:
     image: ruby/single-task
     environment:
       - APPSIGNAL_APP_NAME=ruby-single-task
+      - _TEST_APPSIGNAL_EXTENSION_FAILURE=true
     env_file:
       - ../../appsignal.env
       - ../../appsignal_key.env
```

### Transaction error

```
ERROR: AppSignal failed to load extension. Please run `appsignal diagnose` and email us at support@appsignal.com
LoadError: cannot load such file -- appsignal_extension
/integration/lib/appsignal/transaction.rb:349:in `finish_event': undefined method `finish_event' for nil:NilClass (NoMethodError)
	from /integration/lib/appsignal/helpers/instrumentation.rb:529:in `ensure in instrument'
	from /integration/lib/appsignal/helpers/instrumentation.rb:529:in `instrument'
	from /integration/lib/appsignal/integrations/object.rb:31:in `block in appsignal_instrument_method'
	from app.rb:44:in `block in <main>'
	from app.rb:34:in `times'
	from app.rb:34:in `<main>'
/integration/lib/appsignal/transaction.rb:344:in `start_event': undefined method `start_event' for nil:NilClass (NoMethodError)
	from /integration/lib/appsignal/helpers/instrumentation.rb:524:in `instrument'
	from /integration/lib/appsignal/integrations/object.rb:31:in `block in appsignal_instrument_method'
	from app.rb:44:in `block in <main>'
	from app.rb:34:in `times'
	from app.rb:34:in `<main>'
```

### Metric error

```
ERROR: AppSignal failed to load extension. Please run `appsignal diagnose` and email us at support@appsignal.com
LoadError: cannot load such file -- appsignal_extension
Monitor is doing stuff. Params: foo, {:foo=>0}, 0, true
/integration/lib/appsignal/utils/data.rb:24:in `block in map_hash': undefined method `set_string' for nil:NilClass (NoMethodError)
	from /integration/lib/appsignal/utils/data.rb:20:in `each'
	from /integration/lib/appsignal/utils/data.rb:20:in `map_hash'
	from /integration/lib/appsignal/utils/data.rb:10:in `generate'
	from /integration/lib/appsignal/helpers/metrics.rb:35:in `increment_counter'
	from app.rb:29:in `perform'
	from /integration/lib/appsignal/integrations/object.rb:32:in `block (2 levels) in appsignal_instrument_method'
	from /integration/lib/appsignal/helpers/instrumentation.rb:525:in `instrument'
	from /integration/lib/appsignal/integrations/object.rb:31:in `block in appsignal_instrument_method'
	from app.rb:36:in `block (2 levels) in <main>'
	from /integration/lib/appsignal/helpers/instrumentation.rb:77:in `monitor_transaction'
	from app.rb:35:in `block in <main>'
	from app.rb:34:in `times'
	from app.rb:34:in `<main>'
```

### Transaction error

```
ERROR: AppSignal failed to load extension. Please run `appsignal diagnose` and email us at support@appsignal.com
LoadError: Could not open library '/integration/lib/appsignal/extension/../../../ext/libappsignal.so' : /integration/lib/appsignal/extension/../../../ext/libappsignal.so: cannot open shared object file: No such file or directory
NoMethodError: undefined method `finish_event' for nil:NilClass
  finish_event at /integration/lib/appsignal/transaction.rb:349
    instrument at /integration/lib/appsignal/helpers/instrumentation.rb:527
       perform at /integration/lib/appsignal/integrations/object.rb:31
        app.rb at app.rb:45
        <main> at app.rb:35
```

### Metric error

```
ERROR: AppSignal failed to load extension. Please run `appsignal diagnose` and email us at support@appsignal.com
LoadError: Could not open library '/integration/lib/appsignal/extension/../../../ext/libappsignal.so' : /integration/lib/appsignal/extension/../../../ext/libappsignal.so: cannot open shared object file: No such file or directory
Monitor is doing stuff. Params: foo, {:foo=>0}, 0, true
NameError: undefined method `appsignal_free_data' for class `#<Class:0x662f5666>'
               method at org/jruby/RubyKernel.java:2168
           initialize at /integration/lib/appsignal/extension/jruby.rb:385
         data_map_new at /integration/lib/appsignal/extension/jruby.rb:220
             map_hash at /integration/lib/appsignal/utils/data.rb:19
             generate at /integration/lib/appsignal/utils/data.rb:10
    increment_counter at /integration/lib/appsignal/helpers/metrics.rb:35
              perform at app.rb:29
              perform at /integration/lib/appsignal/integrations/object.rb:32
           instrument at /integration/lib/appsignal/helpers/instrumentation.rb:525
              perform at /integration/lib/appsignal/integrations/object.rb:31
               app.rb at app.rb:36
  monitor_transaction at /integration/lib/appsignal/helpers/instrumentation.rb:77
               app.rb at app.rb:35
               <main> at app.rb:34
```

**Comment by tombruijn** [comment]
The fix for this was released in version 3.0.3
