### ISSUE TITLE
NoMethodError is raised using AppSignal gem with Puma 6

### ISSUE THREAD

**Issue by vdbilt** [appsignal/appsignal-ruby#886]
NoMethodError is raised using AppSignal gem with Puma 6:

```
=> Booting Puma
=> Rails 7.0.4 application starting in development 
Exiting
/usr/local/bundle/gems/appsignal-3.1.4/lib/puma/plugin/appsignal.rb:14:in `start': undefined method `debug' for #<Puma::Events:0x00007feca31c7950 @hooks={}> (NoMethodError)
Did you mean?  debugger
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/plugin.rb:24:in `block in fire_starts'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/plugin.rb:22:in `each'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/plugin.rb:22:in `fire_starts'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/launcher.rb:179:in `run'
	from /usr/local/bundle/gems/puma-6.0.0/lib/rack/handler/puma.rb:72:in `run'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:327:in `start'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

- Using AppSignal for Ruby gem version 3.1.4 and Puma 6.0.0
- Starting the app immediately raises the error

**Comment by tombruijn** [comment]
@vdbilt I have pushed the fix for this in Ruby gem 3.1.5.
