### ISSUE TITLE
Can't run under truffleruby

### ISSUE THREAD

**Issue by matthewford** [appsignal/appsignal-ruby#894]
appsignal (3.1.6)
truffleruby-22.3.0

ERROR: AppSignal failed to load extension. Please run `appsignal diagnose` and email us at support@appsignal.com
LoadError: cannot load such file -- appsignal_extension
rake aborted!
LoadError: cannot load such file -- pty
<internal:core> core/kernel.rb:236:in `gem_original_require'
/home/runner/work/FoodbankWeb/FoodbankWeb/vendor/bundle/truffleruby/3.0.3.22.3.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'

**Comment by tombruijn** [comment]
@matthewford Thanks for creating the issue!

Could you also send us a diagnose report from the machine that raised this error: https://docs.appsignal.com/ruby/command-line/diagnose.html

That way we can compare our own results when we try and reproduce this.

Technical note: Noemi says it should install the C extension, not the FFI extension. Let's make sure it install the correct gem version (java/C-extension).

**Comment by tombruijn** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue.
