### ISSUE TITLE
Error in STDOUT about unable to log sql events

### ISSUE THREAD

**Issue by andyjeffries** [appsignal/appsignal-ruby#999]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

A clear and concise description of what the bug is including the code used and the exception backtrace, if any.

```
Could not log "sql.active_record" event. TypeError: wrong argument type Logtail::Events::SQLQuery (expected String) ["/usr/local/bundle/gems/appsignal-3.4.12/lib/appsignal/logger.rb:54:in `log'", "/usr/local/bundle/gems/appsignal-3.4.12/lib/appsignal/logger.rb:54:in `add'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/logger.rb:26:in `block (2 levels) in broadcast'", "/usr/local/lib/ruby/3.2.0/logger.rb:689:in `debug'", "/usr/local/bundle/gems/logtail-rails-0.2.4/lib/logtail-rails/active_record/log_subscriber/logtail_log_subscriber.rb:32:in `sql'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/subscriber.rb:149:in `finish'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/log_subscriber.rb:115:in `finish'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:211:in `finish'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:76:in `block in finish'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:90:in `each'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:76:in `finish'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'", "/usr/local/bundle/gems/appsignal-3.4.12/lib/appsignal/integrations/active_support_notifications.rb:72:in `finish_with_state'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/instrumenter.rb:30:in `instrument'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:636:in `raw_execute'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:202:in `execute_and_free'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `exec_query'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/querying.rb:54:in `_query_by_sql'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/querying.rb:50:in `find_by_sql'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/statement_cache.rb:150:in `execute'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:232:in `find_target'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/singular_association.rb:44:in `find_target'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:173:in `load_target'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:67:in `reload'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/singular_association.rb:11:in `reader'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/builder/association.rb:104:in `blob'", "/usr/local/bundle/gems/activestorage-7.0.7.2/app/models/active_storage/attachment.rb:79:in `purge_dependent_blob_later'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:400:in `block in make_lambda'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:261:in `block in conditional'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:599:in `block in invoke_after'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:599:in `each'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:599:in `invoke_after'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:108:in `run_callbacks'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:929:in `_run_commit_callbacks'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/transactions.rb:321:in `committed!'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:345:in `block in within_new_transaction'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'", "/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/transactions.rb:294:in `destroy'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/relation.rb:580:in `each'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/relation.rb:580:in `destroy_all'", "/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/querying.rb:22:in `destroy_all'", "(irb):1:in `<main>'", "/usr/local/lib/ruby/3.2.0/irb/workspace.rb:119:in `eval'", "/usr/local/lib/ruby/3.2.0/irb/workspace.rb:119:in `evaluate'", "/usr/local/lib/ruby/3.2.0/irb/context.rb:502:in `evaluate'", "/usr/local/lib/ruby/3.2.0/irb.rb:588:in `block (2 levels) in eval_input'", "/usr/local/lib/ruby/3.2.0/irb.rb:777:in `signal_status'", "/usr/local/lib/ruby/3.2.0/irb.rb:567:in `block in eval_input'", "/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:267:in `block (2 levels) in each_top_level_statement'", "/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:249:in `loop'", "/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:249:in `block in each_top_level_statement'", "/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:248:in `catch'", "/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:248:in `each_top_level_statement'", "/usr/local/lib/ruby/3.2.0/irb.rb:566:in `eval_input'", "/usr/local/lib/ruby/3.2.0/irb.rb:500:in `block in run'", "/usr/local/lib/ruby/3.2.0/irb.rb:499:in `catch'", "/usr/local/lib/ruby/3.2.0/irb.rb:499:in `run'", "/usr/local/lib/ruby/3.2.0/irb.rb:421:in `start'", "/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/console/console_command.rb:74:in `start'", "/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/console/console_command.rb:19:in `start'", "/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/console/console_command.rb:106:in `perform'", "/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'", "/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'", "/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'", "/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/command/base.rb:87:in `perform'", "/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/command.rb:48:in `invoke'", "/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands.rb:18:in `<main>'", "<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "bin/rails:4:in `<main>'"]
```

This occurs during migration and initial boot (I believe I do some queries in the app during initial boot), likely in all other places too, but I've only recently switched to appsignal's logger.

**Comment by tombruijn** [comment]
Easier to read formatted error:

```
Could not log "sql.active_record" event. TypeError: wrong argument type Logtail::Events::SQLQuery (expected String) [
"/usr/local/bundle/gems/appsignal-3.4.12/lib/appsignal/logger.rb:54:in `log'",
"/usr/local/bundle/gems/appsignal-3.4.12/lib/appsignal/logger.rb:54:in `add'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/logger.rb:26:in `block (2 levels) in broadcast'",
"/usr/local/lib/ruby/3.2.0/logger.rb:689:in `debug'",
"/usr/local/bundle/gems/logtail-rails-0.2.4/lib/logtail-rails/active_record/log_subscriber/logtail_log_subscriber.rb:32:in `sql'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/subscriber.rb:149:in `finish'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/log_subscriber.rb:115:in `finish'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:211:in `finish'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:76:in `block in finish'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:90:in `each'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/fanout.rb:76:in `finish'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'",
"/usr/local/bundle/gems/appsignal-3.4.12/lib/appsignal/integrations/active_support_notifications.rb:72:in `finish_with_state'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/notifications/instrumenter.rb:30:in `instrument'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:636:in `raw_execute'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:202:in `execute_and_free'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `exec_query'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/querying.rb:54:in `_query_by_sql'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/querying.rb:50:in `find_by_sql'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/statement_cache.rb:150:in `execute'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:232:in `find_target'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/singular_association.rb:44:in `find_target'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:173:in `load_target'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:67:in `reload'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/singular_association.rb:11:in `reader'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/associations/builder/association.rb:104:in `blob'",
"/usr/local/bundle/gems/activestorage-7.0.7.2/app/models/active_storage/attachment.rb:79:in `purge_dependent_blob_later'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:400:in `block in make_lambda'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:261:in `block in conditional'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:599:in `block in invoke_after'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:599:in `each'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:599:in `invoke_after'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:108:in `run_callbacks'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:929:in `_run_commit_callbacks'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/transactions.rb:321:in `committed!'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:345:in `block in within_new_transaction'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
"/usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/transactions.rb:294:in `destroy'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/relation.rb:580:in `each'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/relation.rb:580:in `destroy_all'",
"/usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/querying.rb:22:in `destroy_all'",
"(irb):1:in `<main>'",
"/usr/local/lib/ruby/3.2.0/irb/workspace.rb:119:in `eval'",
"/usr/local/lib/ruby/3.2.0/irb/workspace.rb:119:in `evaluate'",
"/usr/local/lib/ruby/3.2.0/irb/context.rb:502:in `evaluate'",
"/usr/local/lib/ruby/3.2.0/irb.rb:588:in `block (2 levels) in eval_input'",
"/usr/local/lib/ruby/3.2.0/irb.rb:777:in `signal_status'",
"/usr/local/lib/ruby/3.2.0/irb.rb:567:in `block in eval_input'",
"/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:267:in `block (2 levels) in each_top_level_statement'",
"/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:249:in `loop'",
"/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:249:in `block in each_top_level_statement'",
"/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:248:in `catch'",
"/usr/local/lib/ruby/3.2.0/irb/ruby-lex.rb:248:in `each_top_level_statement'",
"/usr/local/lib/ruby/3.2.0/irb.rb:566:in `eval_input'",
"/usr/local/lib/ruby/3.2.0/irb.rb:500:in `block in run'",
"/usr/local/lib/ruby/3.2.0/irb.rb:499:in `catch'",
"/usr/local/lib/ruby/3.2.0/irb.rb:499:in `run'",
"/usr/local/lib/ruby/3.2.0/irb.rb:421:in `start'",
"/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/console/console_command.rb:74:in `start'",
"/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/console/console_command.rb:19:in `start'",
"/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/console/console_command.rb:106:in `perform'",
"/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'",
"/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'",
"/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'",
"/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/command/base.rb:87:in `perform'",
"/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/command.rb:48:in `invoke'",
"/usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands.rb:18:in `<main>'",
"<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'",
"<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'",
"/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'",
"bin/rails:4:in `<main>'"
]
```

**Comment by andyjeffries** [comment]
Thanks @tombruijn

**Comment by andyjeffries** [comment]
In case it matters, the logger is defined like this in my `config/environments/production.rb` file:

```ruby
console_logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
config.logger = console_logger.extend(
  ActiveSupport::Logger.broadcast(Appsignal::Logger.new("rails", level: config.log_level))
)

```

**Comment by tombruijn** [comment]
This doesn't happen on our Rails 7.0 test apps.

Looks like there's another gem involved here: [logtail-rails 0.2.4](https://rubygems.org/gems/logtail-rails/versions/0.2.4)?

We'd have to test with that gem and see what happens. Looks like it modifies the log event to a `Logtail::Events::SQLQuery` which we don't support and our extension raises an argument error.
